// <auto-generated />
namespace CSharpEgitimKampi301.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mlg1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mlg1));
        
        string IMigrationMetadata.Id
        {
            get { return "202411151357231_mlg1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
